# Generated by Django 3.2.13 on 2022-05-23 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'processing'), ('c', 'completed'), ('r', 'rejected')], default='p', help_text='Order status', max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.CharField(help_text='Client name and surname', max_length=100, verbose_name="Client's full name"),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderlines', to='autoservice.order'),
        ),
    ]
