# Generated by Django 3.2.13 on 2022-06-01 18:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_auto_20220601_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
